### ISSUE TITLE
Feedback on 'Convert to/from JSON'

### ISSUE THREAD

**Issue by pa0dow** [node-red/cookbook.nodered.org#100]
with function inject is all  clear and good
but how with the following string
"hum= 38.00% , temp= 24.00°C , hic= 23.45°C , CO= 120"

Unexpected token h in JSON at position 0?

Dick

**Comment by knolleary** [comment]
Hi @pa0dow,

this recipe is about handling JSON data. Your string is not JSON, so this recipe doesn't apply.

Please use the forum for general how-to questions - https://discourse.nodered.org.

**Comment by pa0dow** [comment]
THANKS
I look for another solution
Dick
