### ISSUE TITLE
Feedback on 'Publish messages to a topic'

### ISSUE THREAD

**Issue by BillClarkEarthPoint** [node-red/cookbook.nodered.org#114]
Please give examples of what the msg would look like to set the topic, qos, or retain, per the instruction "Leave topic, qos, or retain blank if you want to send them via msg properties".

**Comment by dceejay** [comment]
Or inport the flow to the editor and play/experiment with it. (much easier to read/understand)

**Comment by BillClarkEarthPoint** [comment]
thanks

Best regards,

Bill Clark
www.earthpoint.us<http://www.earthpoint.us/>
(208) 860-6311
