### ISSUE TITLE
Feedback on 'Create an HTTP Endpoint'

### ISSUE THREAD

**Issue by ahakobyan79** [node-red/cookbook.nodered.org#117]
How can one set custom timeout on "http in" node ?

**Comment by knolleary** [comment]
Hi - this isn't the best place to ask general support questions - this issue list is more for any problems related to the cookbook recipes.

The community forum - https://discourse.nodered.org - is the best place to ask questions.

In this instance, the `http in` node doesn't provide any way to customise the timeout applied to that route.
