### ISSUE TITLE
Feedback on 'Create an HTTP Endpoint'

### ISSUE THREAD

**Issue by UnmitigatedAudacity** [node-red/cookbook.nodered.org#119]
I'm using NR with Home Assistant and I'm not sure if that makes a difference, but URLs given in the examples is:
`http://localhost:1880/hello`
but I get an error "Cannot GET /hello". Research shows it should be:
`http://localhost:1880/endpoint/hello`
which works fine. Would have saved some time if the examples were correct.

**Comment by knolleary** [comment]
Home Assistant applies a different configuration to the default one provided by Node-RED.

It mounts all http nodes under the `endpoint` URL.

The examples in the cookbook are aimed at the wider Node-RED audience, not just HA.
