### ISSUE TITLE
Feedback on 'Connect to an MQTT Broker'

### ISSUE THREAD

**Issue by dickdow** [node-red/cookbook.nodered.org#133]
your advice
To connect to non-local, secured brokers, other MQTT Config node options will need to be set according to your broker’s connectivity requirements.

But how do yuo in noder?
Dick

**Comment by knolleary** [comment]
Hi,

The MQTT config node includes all of the options needed to connect to secured MQTT Brokers. The specifics will depend on what your broker requires. The config node can be configured with username/password and clientId.

**Comment by dickdow** [comment]
thanks
Mqtt is working well with a local adres 192.168.1.158. But i will use a broker from outside.
Dick
