### ISSUE TITLE
Feedback on 'Node-RED Cookbook'

### ISSUE THREAD

**Issue by AnnaPScofano** [node-red/cookbook.nodered.org#21]
Why are some links missing in the examples? thanks!

**Comment by mblackstock** [comment]
Thanks for the feedback.  Can you let me know what example links are no longer working?  We'll try to fix those up.

**Comment by AnnaPScofano** [comment]
Hi! Below those that have no link. The page is "https://cookbook.nodered.org/".

---- Flow control-----------------------------------------------
Route a message based on one of its properties
Route a message based on a context property
Perform an operation on each element in an array
Trigger a flow if a message isn’t received after a defined time
Limit the rate of messages passing through a flow
Trigger a flow when a message property changes value
Create a simple state machine

---- Error handling --------------------------------------------
Trigger a flow when a node throws an error
Automatically retry an action after an error

---- Working with data formats -------------------------------
Convert to/from JSON
Convert to/from XML
Convert to/from YAML
Convert to/from CSV
Extracting data from an HTML page
Split text into one message per line
------------------------------------------------------------------

The other links are ok!
thanks :-)

**Comment by mblackstock** [comment]
Ok, that's because these cookbook pages haven't been written yet, but we plan to at some point.   If you'd like to help with these, my suggestion is to get on the node-red slack https://nodered.org/slack on the #docs channel and we can tell you how to help.
