### ISSUE TITLE
Feedback on 'Serve a local file'

### ISSUE THREAD

**Issue by AnnaPScofano** [node-red/cookbook.nodered.org#22]
Hello! The "file-in" node has been replaced by "file-path-to-buffer". (https://cookbook.nodered.org/http/serve-a-local-file)
thanks!

**Comment by mblackstock** [comment]
the file nodes under 'storage' are still part of the core and haven't been replaced.  Not sure where to find 'file-path-to-buffer' node.  Tried this example and it works fine.  Suggest contacting the community on [slack](https://nodered.org/slack) #docs or the mailing list in case there is a misunderstanding.
