### ISSUE TITLE
Feedback on 'Simple GET request'

### ISSUE THREAD

**Issue by AnnaPScofano** [node-red/cookbook.nodered.org#23]
It does not work anymore because the "google / finance" page has been modified. (https://cookbook.nodered.org/http/simple-get-request)

**Comment by mblackstock** [comment]
Thanks for the report.  Will have a look

**Comment by AnnaPScofano** [comment]
Welcome!

**Comment by mblackstock** [comment]
Assuming this has not been fixed yet, I will leave it open until I've had a look.
