### ISSUE TITLE
Feedback on 'Trigger a flow whenever Node-RED starts'

### ISSUE THREAD

**Issue by tedstriker** [node-red/cookbook.nodered.org#26]
In version 0.18.6 the inject node option to fire once after deploy is not available anymore, despite the documentation says so.

**Comment by dceejay** [comment]
??? 
can you let us know what you are seeing... It should looks like this
(This is a small change to previous - in that we now allow you to set the time... but it shouldn't have disappeared.

![image](https://user-images.githubusercontent.com/5375409/40839917-6c13ba8e-659c-11e8-8b20-aef95294880c.png)

**Comment by tedstriker** [comment]
sorry, my bad. Don't know what I was looking at when I wrote the issue. Everything's fine.
