### ISSUE TITLE
Feedback on 'Delete a message property'

### ISSUE THREAD

**Issue by rajbir123** [node-red/cookbook.nodered.org#29]
Small Feedback for documentation:
Your div block is too small and narrow and need to scroll everytime to check the contents. 
Its too much annoying as content kept in small and narrow div, its make difficult for comparison with respect to other nodes.

Better remove this line which is no use ie max-height and the overflow-y:
div.flow pre {
            /* max-height: 100px; 
           overflow-y: scroll; */
}

**Comment by knolleary** [comment]
Thanks for the feedback; this was an intentional choice as flow json can get quite long and most times a user just wants to copy it, not read it. Flooding the page with json reduces the readability of a recipe.

**Comment by rajbir123** [comment]
@knolleary thnks. 
But thats not the correct way to handle in everywhere. If its relates to flow.json file then u can use that but it has been used everywhere which makes so much annoying as everytime to scroll and make some comparison between the nodes. Pls make it user reliable to read the documentation as easy as it is.

#one more question want to as ask, Is there any other stuffs/material apart from this documentation where i can understand the inside the code flow and the architecture of nodered I mean any videos material apart from this documentation.

**Comment by knolleary** [comment]
@rajbir123 can you link to some examples of non-flow code blocks that have had this style applied?

**Comment by knolleary** [comment]
@rajbir123 sorry, I did misunderstand:

> If its relates to flow.json file then u can use that but it has been used everywhere

I read that to mean you didn't mind it being used for flow file, but that is had been used 'everywhere'. So I was curious to know what you mean by everywhere other than flow files.

I do take your point - I'm sure there's a better answer that helps keep it readable without flooding the page.

**Comment by rajbir123** [comment]
@knolleary thank you so much for your kind reply, I am your big fan :) actually I love Node Red flow based programming.
I have one more issue or doubt. It may be bug or feature that u have been added. 
In node red dashboard palette, if i want to customize the name of node suppose HTTP-response but what I see by default dash (-) is replaced by space and it always give HTTP response. I want to make it HTTP-response, so please let me know where and what to change.

**Comment by knolleary** [comment]
@rajbir123 When displaying node types in the palette, it automatically replaces `-` with spaces. That's just what it does - there's nothing you can do about it.

Please don't use this as a general thread for questions - the [https://discourse.nodered.org](Node-RED Forum) is available for that.

**Comment by knolleary** [comment]
You can use the dash in the name, but when it is displayed it will get replaced with a space.

To repeat my response: That's just what it does - there's nothing you can do about it.

Can I ask why you want the existing HTTP Response node to be presented as http-response or are you just using that as an example?

**Comment by rajbir123** [comment]
@knolleary   thats just an example.. Nick, Actually I am trying to make my own custom node with such name with dash - so please tell me how to achieve this.

**Comment by knolleary** [comment]
For the third time: there's nothing you can do about it in your node. That is just what the palette does when displaying node labels.

https://github.com/node-red/node-red/blob/69448c73290ca59ae8430ff6d64bfa41f77bfc4a/editor/js/ui/palette.js#L75
