### ISSUE TITLE
Feedback on 'Set the URL of a request using a template'

### ISSUE THREAD

**Issue by knolleary** [node-red/cookbook.nodered.org#3]
The intent of this recipe was to set the url using the node's built-in templating functionality - not to use a Template node.

I would suggest the problem statement should be:

> You want to dynamically set the URL of an HTTP request where only parts of the url change between requests.

**Comment by mblackstock** [comment]
I'll change the problem statement as suggested and use the built in templating.

**Comment by mblackstock** [comment]
fixed a while back
