### ISSUE TITLE
Is monitor the CPU load enough to understand if we have this problem?

### ISSUE THREAD

**Issue by Barabba11** [node-red/cookbook.nodered.org#40]
Can we simply monitor CPU, better daily graph of CPU usage, to be sure we haven't benn hacked?
Can you please explain how to wipe service (as you suggested) and reinstall it safely without reinstall Raspbian and reconfigure all? (in my case not few time)
Are modules in github (or installing by palette) possible infected? Or the hack can come ony from internet?
How to change the TCP port number listening?

SOrry for lot of questions, thanks for help!

**Comment by knolleary** [comment]
Hi @Barabba11 

this is the issue tracker for the Node-RED Cookbook. Whilst you've asked some very good questions here, they are unrelated to the cookbook.

Can I suggest you ask your questions on the [Node-RED forum](https://discourse.nodered.org) where the wider user community can join the conversation.
