### ISSUE TITLE
Two similar links to /http/simple-get-request from Table of Content.

### ISSUE THREAD

**Issue by ryoichi-obara** [node-red/cookbook.nodered.org#54]
Are you sure you want to link to page under http category from basic?

There's a link ``- [Simple GET request](/http/simple-get-request)`` in /_includes/indexes/http.md

There's also a similar link ``- [Extracting data from an HTML page](/http/simple-get-request)`` in /_includes/indexes/basic.md

**Comment by knolleary** [comment]
Yes.

Some users will arrive at the page wanting to know how to parse information from an HTML page. Some will want to know how to get the content of an HTML page. The same recipe answers both questions.
