### ISSUE TITLE
Feedback on 'Trigger a flow whenever Node-RED starts'

### ISSUE THREAD

**Issue by torbenvaering** [node-red/cookbook.nodered.org#59]
From this sentence: "Use an Inject node configured to fire once on start."

Please explain HOW to configure an inject node to fire once on start. :-)

**Comment by knolleary** [comment]
We can certainly clarify that in the recipe, but if you are asking how to do that, you should edit the Inject node and tick the box next to "Inject once after 0.1 seconds".

**Comment by torbenvaering** [comment]
Hey – thanks for getting back 😊
I found out, but thanks anyway. Iit was just a suggestion to improve for beginners 😊

Fra: knolleary <notifications@github.com>
Sendt: 10. august 2019 15:29
Til: node-red/cookbook.nodered.org <cookbook.nodered.org@noreply.github.com>
Cc: Torben Væring <tv@infoba.dk>; Author <author@noreply.github.com>
Emne: Re: [node-red/cookbook.nodered.org] Feedback on 'Trigger a flow whenever Node-RED starts' (#59)


We can certainly clarify that in the recipe, but if you are asking how to do that, you should edit the Inject node and tick the box next to "Inject once after 0.1 seconds".
