### ISSUE TITLE
Feedback on 'Set the URL of a request'

### ISSUE THREAD

**Issue by juansolanop** [node-red/cookbook.nodered.org#68]
I believe this page is outdated, please check:

https://github.com/node-red/node-red/wiki/Deprecated:-Message-properties-overriding-set-node-properties

if there is a workaround for this limitation can you please also include the reference?

**Comment by knolleary** [comment]
Hi @juansolanop 

what about it do you believe is outdated?

The HTTP Request node in the provided flow does not have its `url` property set, so it can be overridden by the `msg.url` property it receives.
