### ISSUE TITLE
Feedback on 'Create an HTTP Endpoint'

### ISSUE THREAD

**Issue by jim-moyse** [node-red/cookbook.nodered.org#70]
I am attempting to learn how to use Node Red for a project that I am working on.  I have installed Node Red on my workstation it appears to be working correctly.  Opening Node-red @ 127.0.0.1:1880. 

Using the Node Red Cookbook as a tutorial, I am trying to generate an interactive web page.  Starting with HTTP endpoints, I follow the instructions, get a HTTP In node, a Template node, HTTP Response node and wire them together.  I add the HTML code to the Template node.

What address do I put in the browser to see "Hello World"?  127.0.0.1:1880/???

I am missing how to view the response and need this most basic step to move on.

Thanks,

Jim

**Comment by mblackstock** [comment]
At the bottom of the page in the discussion section, it suggests using curl to access the endpoint `http://localhost:1880/hello`.  You would point the browser to that. 

> If you have turned on http authentication then you may need add your userid and password to the curl command. e.g.
> ```
> [~]$ curl -u userid:password  http://localhost:1880/hello 
> ```
>

**Comment by jim-moyse** [comment]
Thanks.  It makes sense now.

________________________________
