### ISSUE TITLE
Feedback on 'Trigger a flow at regular intervals'

### ISSUE THREAD

**Issue by jamestharpe** [node-red/cookbook.nodered.org#73]
Please include instructions to stop the flow once it has been started.

**Comment by knolleary** [comment]
You eithet change the Inject node's configuration to not inject repeatedly or you delete it. Then deploy those changes.

**Comment by jamestharpe** [comment]
Right. This should be reflected in the documentation.

**Comment by knolleary** [comment]
Fair enough. I took it as a given that to stop a node from doing what you've configured it to do, you would either delete it or change its configuration. Will consider that for the next update.
