### ISSUE TITLE
Feedback on 'Post JSON data to a flow'

### ISSUE THREAD

**Issue by ddevashish** [node-red/cookbook.nodered.org#76]
There is no any Json implemented in the example

**Comment by knolleary** [comment]
Hi @ddevashish 

can you explain a bit more what you mean?

The recipe shows how you can create a flow that accepts JSON data that is posted to it via an HTTP request.

It includes an example `curl` command that can be used to send the POST with the JSON data `{"name":"Nick"}`.

**Comment by ddevashish** [comment]
Title shows 'Post Json data to a flow'

But there is no any JSON object or json node available in the example


[{"id":"5b98a8ac.a46758","type":"http in","z":"3045204d.cfbae","name":"","url":"/hello-form","method":"post","swaggerDoc":"","x":120,"y":820,"wires":[["bba61009.4459f"]]},{"id":"bba61009.4459f","type":"template","z":"3045204d.cfbae","name":"page","field":"payload","fieldType":"msg","format":"handlebars","syntax":"mustache","template":"<html>\n    <head></head>\n    <body>\n        <h1>Hello {{ payload.name }}!</h1>\n    </body>\n</html>","x":290,"y":820,"wires":[["6ceb930a.93146c"]]},{"id":"6ceb930a.93146c","type":"http response","z":"3045204d.cfbae","name":"","x":430,"y":820,"wires":[]}]

**Comment by knolleary** [comment]
Correct. The recipe is about creating a flow that can *receive* an HTTP Post containing JSON data.
