### ISSUE TITLE
Feedback on 'Parse CSV input'

### ISSUE THREAD

**Issue by Nitesh-bit1991** [node-red/cookbook.nodered.org#78]
how to add the tag key when ''Parse CSV input''. the csv file  is successfull  seen in debud but I want to see the csv file with tag key in influxdb. 

I tried with this:
msg.payload = [{
    Vlaue:"home1.csv" ,#file name home1
},
{
    tag:"COIL_ID",# want to use this tag in my csv file
}];
return msg;

**Comment by dceejay** [comment]
As per the issue form you have managed to delete - we prefer general how-to questions via either slack or the discourse forum, where a much larger audience can help. As this in particular is about influxdb, that none of the core team use, and now nothing about. - I'm going to close it here and let you ask in the forum instead
