### ISSUE TITLE
Feedback on 'Trigger a flow whenever Node-RED starts'

### ISSUE THREAD

**Issue by danieldean1** [node-red/cookbook.nodered.org#86]
I ended up here after trying to find a way to trigger multiple injects at once to a device - could someone help with the best method for doing this? Thank you.\

This, like other cookbook flows, is very thin on info for the beginner. This states when configured to do, the inject node will fire on node red starting ...but then don't show any configuration of the node, only the graphical node and it's connection. It would be very helpful to have the flow code for inspecting in situ.

**Comment by knolleary** [comment]
If you click the 'show flow' button on the page, you'll get the flow JSON you can import into the editor.

**Comment by danieldean1** [comment]
(facepalm) thank you, wow, you would think I haven't interwebbed before...it's all a guy could want, gracias.
