### ISSUE TITLE
Feedback on 'Drop messages that have not changed value'

### ISSUE THREAD

**Issue by nonujigu** [node-red/cookbook.nodered.org#94]
It would be great if the rbe node had the ability to get all internally stored messages when the "Apply mode for each msg.topic separately" property is set (possibly with a seperate output). Similar to the msg.complete property in the join node's manual mode. I recently found out that it is almost possible to get this behaviour with the trigger node (if the Handling is set to  "each msg.topic"). The problem with the trigger node is that the actual trigger is always time triggerd and a msg.complete property similar to the join node's manual mode is not supported.

**Comment by knolleary** [comment]
Hi @nonujigu 

the best place to make feature requests/suggestions is the forum here: discourse.nodered.org.

This issue list is for feedback on the cookbook content itself, rather than the functionality of Node-RED.

**Comment by dceejay** [comment]
The only thing stored is the previous message per topic - and that has already been sent - so you have it once already. The idea of the RBE node is to not send things multiple times.

**Comment by nonujigu** [comment]
> Hi @nonujigu
> 
> the best place to make feature requests/suggestions is the forum here: https://discourse.nodered.org.
> 
> This issue list is for feedback on the cookbook content itself, rather than the functionality of Node-RED.

Hi @knolleary Thanks for the hint.

**Comment by nonujigu** [comment]
@knolleary @dceejay 

I posted a [new topic in the Node-RED forum](https://discourse.nodered.org/t/storing-latest-messages-by-topic-for-a-possible-request/45343) where I described my actual problem with more context. Steve-Mcl already hinted me to a solution that works with the latest Node-RED version.
