### ISSUE TITLE
Feedback on 'Create an HTTP Endpoint'

### ISSUE THREAD

**Issue by somersaultjump** [node-red/cookbook.nodered.org#96]
The example in this documentation is not working.
https://cookbook.nodered.org/http/create-an-http-endpoint#example

I've imported the flow and ran exactly how it is shown here, an it results in a 404 each time.

It's worth noting that the current node shows that any URL is appended to "/endpoint", which is not referenced anywhere in the documentation. The request returns a 404 regardless if the "/endpoint" is present or not.

I'm not terribly familiar with node red, as I've only just started using it, so it's entirely possible I'm missing something.

**Comment by somersaultjump** [comment]
I'm running node red version 9.1.3

**Comment by mblackstock** [comment]
I'm not sure what you mean when you say the "current node shows that any URL is appended to /endpoint".  Have you changed your settings.js file?  Are you running node-red locally with a default configuration?

The URL that the flow creates is `/hello`.  I've just tested it locally with a default configuration and it works for me.

**Comment by somersaultjump** [comment]
@knolleary Yes, this is correct, I am running Node-RED on Home Assistant.  As I said, I've only just recently picked up Node-RED and clearly, I have some more research to do, specifically with how its implemented in HA. 

Thank you both for the quick replies.
